"""chat_memories per group

Revision ID: 4614938e5fc5
Revises: 64bb0ad00480
Create Date: 2026-09-07 15:39:41.510941
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4614938e5fc5'
down_revision: str | Sequence[str] | None = '64bb0ad00480'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_memories',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.drop_table('thread_memories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_memories',
    sa.Column('thread_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], name=op.f('thread_memories_thread_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id', name=op.f('thread_memories_pkey'))
    )
    op.drop_table('chat_memories')
    # ### end Alembic commands ###
