"""agy_session send target

Revision ID: 64bb0ad00480
Revises: 778d4df2cc88
Create Date: 2026-09-07 15:16:17.393623
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '64bb0ad00480'
down_revision: str | Sequence[str] | None = '778d4df2cc88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agy_sessions', sa.Column('trigger_tg_message_id', sa.BigInteger(), nullable=True))
    op.add_column('agy_sessions', sa.Column('sent_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agy_sessions', 'sent_count')
    op.drop_column('agy_sessions', 'trigger_tg_message_id')
    # ### end Alembic commands ###
