"""scheduled_tasks

Revision ID: 778d4df2cc88
Revises: 92f9def73dc1
Create Date: 2026-09-07 15:00:14.824677
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '778d4df2cc88'
down_revision: str | Sequence[str] | None = '92f9def73dc1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('cron', sa.String(length=128), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.String(length=512), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_tasks_enabled_run_at', 'scheduled_tasks', ['enabled', 'run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_tasks_enabled_run_at', table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
