"""initial schema

Revision ID: 92f9def73dc1
Revises: 
Create Date: 2026-09-07 14:23:15.846952
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '92f9def73dc1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_threads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('chat_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'topic_id', name='uq_chat_threads_chat_topic')
    )
    op.create_table('agy_sessions',
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_key')
    )
    op.create_index('ix_agy_sessions_expires_at', 'agy_sessions', ['expires_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=True),
    sa.Column('from_username', sa.String(length=256), nullable=True),
    sa.Column('from_name', sa.String(length=512), nullable=True),
    sa.Column('is_bot_self', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'tg_message_id', name='uq_messages_thread_tg')
    )
    op.create_index('ix_messages_thread_sent_at', 'messages', ['thread_id', 'sent_at'], unique=False)
    op.create_table('thread_memories',
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread_memories')
    op.drop_index('ix_messages_thread_sent_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_agy_sessions_expires_at', table_name='agy_sessions')
    op.drop_table('agy_sessions')
    op.drop_table('chat_threads')
    # ### end Alembic commands ###
